// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    return $.getJSON("ce.json", function(data) {
      var html, i, item, _i, _ref, _results;
      _results = [];
      for (i = _i = 1, _ref = data.length - 1; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        item = data[i];
        html = "<tr><td>" + item[0] + "</td><td>" + item[1] + "</td><td>" + item[2] + "</td></tr>";
        _results.push($("#table-content").append(html));
      }
      return _results;
    });
  });

}).call(this);
